### ISSUE TITLE
Error on gradlew run

### ISSUE THREAD

**Issue by sotengboy** [bladh/pokerbot#18] opened 2022-06-08 06:38 UTC
Hello I just install pokerbot on my Centos Server and I got this error

```
Invalid stats file: java.io.EOFException
irc.bagusin.id:6667
1654670223739 *** Connected to server.
1654670223744 *** Logged onto server.
java.net.SocketException: Socket is closed
        at java.net.Socket.setSoTimeout(Socket.java:1155)
        at sun.security.ssl.BaseSSLSocketImpl.setSoTimeout(BaseSSLSocketImpl.java:637)
        at sun.security.ssl.SSLSocketImpl.setSoTimeout(SSLSocketImpl.java:73)
        at org.jibble.pircbot.PircBot.connect(PircBot.java:239)
        at org.jibble.pircbot.PircBot.connect(PircBot.java:121)
        at me.ars.pokerbot.Main.main(Main.java:28)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings
```

what's the problem?

**Comment by bladh** [comment] 2023-01-28 06:04
The problem in this case may have been caused by the old ircbot framework used by the bot. I have now replaced it with a more stable and maintained solution and have since been able to connect to `irc.bagusin.id`.

**Comment by bladh** [comment] 2024-04-11 08:47
Closing this issue since it seems to have been solved.

**Closed as completed by bladh** 2024-04-11 08:47 UTC
